In [1]:
print("JAY BABA PANCHBADAN")

JAY BABA PANCHBADAN


In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler

from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

import xgboost as xgb

from sklearn.neighbors import KNeighborsClassifier


In [4]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv"

In [7]:
df = pd.read_csv(url,sep=";")


In [8]:
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [9]:
df.tail()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6

In [10]:
df["quality"].value_counts()


quality
5    681
6    638
7    199
4     53
8     18
3     10
Name: count, dtype: int64

In [12]:
df["quality"].max()

np.int64(8)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [14]:
df.describe()


fixed acidity  volatile acidity  citric acid  residual sugar  \
count    1599.000000       1599.000000  1599.000000     1599.000000   
mean        8.319637          0.527821     0.270976        2.538806   
std         1.741096          0.179060     0.194801        1.409928   
min         4.600000          0.120000     0.000000        0.900000   
25%         7.100000          0.390000     0.090000        1.900000   
50%         7.900000          0.520000     0.260000        2.200000   
75%         9.200000          0.640000     0.420000        2.600000   
max        15.900000          1.580000     1.000000       15.500000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  1599.000000          1599.000000           1599.000000  1599.000000   
mean      0.087467            15.874922             46.467792     0.996747   
std       0.047065            10.460157             32.895324     0.001887   
min       0.012000             1.000000              6.000000     0.990070   
25%       0.070000             7.000000             22.000000     0.995600   
50%       0.079000            14.000000             38.000000     0.996750   
75%       0.090000            21.000000             62.000000     0.997835   
max       0.611000            72.000000            289.000000     1.003690   

                pH    sulphates      alcohol      quality  
count  1599.000000  1599.000000  1599.000000  1599.000000  
mean      3.311113     0.658149    10.422983     5.636023  
std       0.154386     0.169507     1.065668     0.807569  
min       2.740000     0.330000     8.400000     3.000000  
25%       3.210000     0.550000     9.500000     5.000000  
50%       3.310000     0.620000    10.200000     6.000000  
75%       3.400000     0.730000    11.100000     6.000000  
max       4.010000     2.000000    14.900000     8.000000

In [15]:
df.quality

0       5
1       5
2       5
3       6
4       5
       ..
1594    5
1595    6
1596    6
1597    5
1598    6
Name: quality, Length: 1599, dtype: int64

In [16]:
df["quality"]

0       5
1       5
2       5
3       6
4       5
       ..
1594    5
1595    6
1596    6
1597    5
1598    6
Name: quality, Length: 1599, dtype: int64

In [17]:
df["quality"] = df["quality"].apply(lambda x: 1 if x >= 7 else 0)


In [18]:
df.head()


fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        0  
1      9.8        0  
2      9.8        0  
3      9.8        0  
4      9.4        0

In [19]:
x = df.drop("quality",axis=1)
y = df["quality"]





In [22]:
x.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  
0      9.4  
1      9.8  
2      9.8  
3      9.8  
4      9.4

In [23]:
y.tail()

1594    0
1595    0
1596    0
1597    0
1598    0
Name: quality, dtype: int64

In [24]:
y.max()

np.int64(1)

In [25]:
y.value_counts()


quality
0    1382
1     217
Name: count, dtype: int64

In [26]:
scalar = StandardScaler()
x = scalar.fit_transform(x)


In [28]:
x[0]

array([-0.52835961,  0.96187667, -1.39147228, -0.45321841, -0.24370669,
       -0.46619252, -0.37913269,  0.55827446,  1.28864292, -0.57920652,
       -0.96024611])

In [29]:
pd.DataFrame(x)


0         1         2         3         4         5         6   \
0    -0.528360  0.961877 -1.391472 -0.453218 -0.243707 -0.466193 -0.379133   
1    -0.298547  1.967442 -1.391472  0.043416  0.223875  0.872638  0.624363   
2    -0.298547  1.297065 -1.186070 -0.169427  0.096353 -0.083669  0.229047   
3     1.654856 -1.384443  1.484154 -0.453218 -0.264960  0.107592  0.411500   
4    -0.528360  0.961877 -1.391472 -0.453218 -0.243707 -0.466193 -0.379133   
...        ...       ...       ...       ...       ...       ...       ...   
1594 -1.217796  0.403229 -0.980669 -0.382271  0.053845  1.542054 -0.075043   
1595 -1.390155  0.123905 -0.877968 -0.240375 -0.541259  2.211469  0.137820   
1596 -1.160343 -0.099554 -0.723916 -0.169427 -0.243707  1.255161 -0.196679   
1597 -1.390155  0.654620 -0.775267 -0.382271 -0.264960  1.542054 -0.075043   
1598 -1.332702 -1.216849  1.021999  0.752894 -0.434990  0.203223 -0.135861   

            7         8         9         10  
0     0.558274  1.288643 -0.579207 -0.960246  
1     0.028261 -0.719933  0.128950 -0.584777  
2     0.134264 -0.331177 -0.048089 -0.584777  
3     0.664277 -0.979104 -0.461180 -0.584777  
4     0.558274  1.288643 -0.579207 -0.960246  
...        ...       ...       ...       ...  
1594 -0.978765  0.899886 -0.461180  0.072294  
1595 -0.862162  1.353436  0.601055  0.729364  
1596 -0.533554  0.705508  0.542042  0.541630  
1597 -0.676657  1.677400  0.305990 -0.209308  
1598 -0.666057  0.511130  0.010924  0.541630  

[1599 rows x 11 columns]

In [30]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [31]:
x_train[0]

array([ 0.21852997,  0.90601191,  0.20039205,  0.32720732, -0.03116947,
        0.6813767 ,  1.05008877,  1.83030733,  1.09426457,  0.48302886,
        1.10483337])

In [43]:
xgb_model_classifier = xgb.XGBClassifier(objective="binary:logistic",learning_rate=0.1,max_depth=6, eval_metric="logloss")
xgb_model_classifier.fit(x_train,y_train)
y_pred = xgb_model_classifier.predict(x_test)

print(y_pred[0])



0


In [44]:
classifier_report = classification_report(y_test,y_pred)
print(classifier_report)

              precision    recall  f1-score   support

           0       0.93      0.96      0.94       273
           1       0.70      0.55      0.62        47

    accuracy                           0.90       320
   macro avg       0.81      0.76      0.78       320
weighted avg       0.89      0.90      0.89       320



In [45]:
confusion_matrix(y_test,y_pred)


array([[262,  11],
       [ 21,  26]])

In [46]:
accuracy_score(y_test,y_pred)


0.9

In [38]:
y_test.max()

np.int64(1)

In [47]:
x = df.drop("quality",axis=1)
y = df["quality"]

In [54]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=30)


In [55]:
x_train_scaled = scalar.fit_transform(x_train)

x_train_scaled[0]


array([-1.82966333, -0.2150038 , -0.07878943, -0.1625773 ,  0.04015632,
        0.68463082,  0.84074535, -0.79136149,  2.62002588, -0.22128201,
        1.69255006])

In [56]:
x_test_scaled = scalar.transform(x_test)

x_test_scaled[0]


array([ 0.95670065, -0.6624601 ,  0.89807886,  2.71110027, -0.35080467,
       -0.92135989, -0.97137683,  0.1327225 , -0.63521795, -0.96381602,
        1.31547238])

In [ ]:
xgb_model_classifier = xgb.XGBClassifier(objective="binary:logistic",learning_rate=0.1,max_depth=6, eval_metric="logloss")
xgb_model_classifier.fit(x_train_scaled,y_train)
y_pred = xgb_model_classifier.predict(x_test_scaled)

print(y_pred[0])



0


In [58]:
classifier_report = classification_report(y_test,y_pred)
print(classifier_report)




              precision    recall  f1-score   support

           0       0.95      0.95      0.95       278
           1       0.64      0.64      0.64        42

    accuracy                           0.91       320
   macro avg       0.79      0.79      0.79       320
weighted avg       0.91      0.91      0.91       320



In [59]:
confusion_matrix(y_test,y_pred)


array([[263,  15],
       [ 15,  27]])

In [60]:
# use grid search cv to find the best parameters for the model


In [63]:
param_grid = {
    "n_estimators": [100, 200, 300],
    "learning_rate": [0.1, 0.1, .2],
    "max_depth": [3, 4, 5, 6, 7, 8, 9, 10],
    "subsample": [0.5, 0.6, 0.8, 0.9, 1.0],
    "colsample_bytree": [ 0.7, 0.8, 0.9, 1.0],
    "eval_metric": ["logloss", "error", "auc"],
}

In [ ]:
grid_search = GridSearchCV(estimator=xgb_model_classifier, param_grid=param_grid, cv=2, scoring="accuracy", n_jobs=1)
grid_search.fit(x_train_scaled,y_train)

In [ ]:
grid_search.best_params_


In [ ]:
xgb_model_classifier_best_par = xgb.XGBClassifier(**grid_search.best_params_,  objective="binary:logistic",learning_rate=0.1,max_depth=6, eval_metric="logloss")
xgb_model_classifier_best_par.fit(x_train_scaled,y_train)
y_pred = xgb_model_classifier_best_par.predict(x_test_scaled)

print(y_pred[0])




# KNN 

In [65]:
from sklearn.datasets import load_iris


In [66]:
data = load_iris()

x = data.data
y = data.target


In [67]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [68]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [70]:
x = pd.DataFrame(x,columns=data.feature_names)


In [71]:
y = pd.DataFrame(y,columns=["target"])


In [74]:
x.head()






sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [75]:
y.head()

target
0       0
1       0
2       0
3       0
4       0

In [76]:
y.max()

target    2
dtype: int64

In [77]:
scalar = StandardScaler()


In [79]:
x = scalar.fit_transform(x)


In [80]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

x_train[0]

array([-1.50652052,  1.24920112, -1.56757623, -1.3154443 ])

In [81]:
xgb_model_classifier_iris = xgb.XGBClassifier(objective="binary:logistic",learning_rate=0.1,max_depth=6, eval_metric="logloss")
xgb_model_classifier_iris.fit(x_train,y_train)
y_pred = xgb_model_classifier_iris.predict(x_test)

print(y_pred[0])




1


In [82]:
classifier_report = classification_report(y_test,y_pred)
print(classifier_report)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [83]:
confusion_matrix(y_test,y_pred)


array([[10,  0,  0],
       [ 0,  9,  0],
       [ 0,  0, 11]])

In [99]:
knn_classifier_9 = KNeighborsClassifier(n_neighbors=9)
knn_classifier_9.fit(x_train,y_train)
y_pred = knn_classifier_9.predict(x_test)

print(y_pred[0])


1


c:\Users\ravi1\anaconda3\envs\fsds\Lib\site-packages\sklearn\neighbors\_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


In [100]:
accuracy_score(y_test,y_pred)


1.0

In [101]:
classifier_report = classification_report(y_test,y_pred)
print(classifier_report)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [102]:
confusion_matrix(y_test,y_pred)


array([[10,  0,  0],
       [ 0,  9,  0],
       [ 0,  0, 11]])

In [103]:
import pickle

In [89]:
with open("xgb_model_classifier_iris.pkl","wb") as f:
    pickle.dump((xgb_model_classifier_iris, scalar),f)





In [94]:
with open("knn_classifier.pkl","wb") as f:
    pickle.dump((knn_classifier, scalar),f)


In [95]:
param = {
    "n_neighbors":np.arange(1,30,2),
}

In [96]:
grid_knn = GridSearchCV(knn_classifier,param,cv=3, scoring="accuracy", n_jobs=-1)
grid_knn.fit(x_train,y_train)


c:\Users\ravi1\anaconda3\envs\fsds\Lib\site-packages\sklearn\neighbors\_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


GridSearchCV(cv=3, estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'n_neighbors': array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])},
             scoring='accuracy')

In [98]:
grid_knn.best_params_

{'n_neighbors': np.int64(9)}

In [104]:
url = "https://datasets-server.huggingface.co/rows?dataset=Hannan2004%2FDDoS-Attack-Dataset&config=default&split=train&offset=0&length=100"

In [108]:
data = pd.read_json("dataset.json")







In [109]:
pd.DataFrame(data)


log   label
0     {' Flow Duration': 7762311, ' Total Fwd Packet...  BENIGN
1     {' Flow Duration': 7762328, ' Total Fwd Packet...  BENIGN
2     {' Flow Duration': 257921, ' Total Fwd Packets...  BENIGN
3     {' Flow Duration': 70794517, ' Total Fwd Packe...  BENIGN
4     {' Flow Duration': 70793677, ' Total Fwd Packe...  BENIGN
...                                                 ...     ...
996   {' Flow Duration': 660434, ' Total Fwd Packets...    DDoS
997   {' Flow Duration': 2101661, ' Total Fwd Packet...    DDoS
998   {' Flow Duration': 685468, ' Total Fwd Packets...    DDoS
999   {' Flow Duration': 2074956, ' Total Fwd Packet...    DDoS
1000  {' Flow Duration': 670237, ' Total Fwd Packets...    DDoS

[1001 rows x 2 columns]

In [110]:
import json

In [112]:
print("Loading dataset...")
with open('dataset.json', 'r') as file:
    data = json.load(file)
    
# Extract features and labels
features = []
labels = []

for item in data:
    features.append(list(item['log'].values()))
    labels.append(item['label'])

# Convert to numpy arrays
X = np.array(features)
y = np.array(labels)

print(f"Dataset loaded: {X.shape[0]} samples, {X.shape[1]} features")
print(f"Label distribution: {np.unique(y, return_counts=True)}")

Loading dataset...
Dataset loaded: 1001 samples, 30 features
Label distribution: (array(['BENIGN', 'DDoS'], dtype='<U6'), array([341, 660]))


In [114]:
x[0]

array([-0.90068117,  1.01900435, -1.34022653, -1.3154443 ])

In [113]:
# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)